# Generated by Django 4.0.4 on 2022-05-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_code', models.CharField(blank=True, max_length=255, unique=True)),
                ('product_price', models.CharField(blank=True, max_length=255)),
                ('product_desc', models.TextField(blank=True)),
                ('product_stock', models.IntegerField(blank=True)),
            ],
        ),
    ]
