# Generated by Django 4.0.4 on 2022-05-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='product_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
