# Generated by Django 4.0.4 on 2022-05-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0003_alter_productsmodel_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='product_image',
            field=models.ImageField(blank=True, upload_to='product'),
        ),
    ]
