# Generated by Django 4.0.4 on 2022-05-15 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('details', models.TextField()),
                ('attachments', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('closed', 'Closed')], max_length=100)),
                ('complain_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complain_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
