# Generated by Django 4.0.4 on 2022-05-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complainmodel',
            name='suspect',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='complainmodel',
            name='suspect_description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
