# Generated by Django 4.0.4 on 2022-05-16 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0002_complainmodel_suspect_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complainmodel',
            old_name='location',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='complainmodel',
            name='suspect_description',
        ),
    ]
