# Generated by Django 4.0.4 on 2022-05-13 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_remove_blog_sub_category_delete_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
    ]
