# Generated by Django 4.0.4 on 2022-05-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_forumcommentmodel_forumlikesmodel_forummodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='blogimg',
            field=models.ImageField(blank=True, upload_to='blog_image', verbose_name='ADD BLOG IMAGE'),
        ),
    ]
