# Generated by Django 4.0.4 on 2022-05-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_alter_blogmodel_blogimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='blogcontent',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='blogimg',
            field=models.ImageField(blank=True, upload_to='blog_image'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='blogtitle',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='forummodel',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='forummodel',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
