# Generated by Django 4.0.4 on 2022-05-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_alter_blogmodel_blogcontent_alter_blogmodel_blogimg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTagsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='blog_tags', to='blog_app.blogtagsmodel'),
        ),
    ]
