# Generated by Django 4.0.4 on 2022-05-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_blogtagsmodel_blogmodel_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='forummodel',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='forummodel',
            name='title',
        ),
        migrations.AddField(
            model_name='forummodel',
            name='categories',
            field=models.ManyToManyField(related_name='user_forum_categories', to='blog_app.forumcategorymodel'),
        ),
    ]
