# Generated by Django 4.0.4 on 2022-05-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_forumcategorymodel_remove_forummodel_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forummodel',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_forum_categories', to='blog_app.forumcategorymodel'),
        ),
    ]
