# Generated by Django 4.0.4 on 2022-05-31 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_alter_forummodel_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumcommentmodel',
            name='forum_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog_app.forummodel'),
        ),
    ]
